image: nexus:8088/amarises/root
variables:
  TARGET_REPO: https://'bvam':'Lamiasuperpassword!'@bitbucket.org/bvam/testrepo2.git
stages:
  - clone
clone:
  before_script:
    - apt-get update && apt-get install -y git
    - git config --global user.email "bvamaris@gmail.com"
    - git config --global user.name "bvam"
  stage: clone
  script:
    - git remote add remoterepo $TARGET_REPO
    - git push remoterepo master
  only:
    - master